import config

print("=== FILTER SETTINGS DEBUG ===")
print("SR_FILTER_ENABLED =", config.SR_FILTER_ENABLED)
print("SR_PIVOT_POINTS_ENABLED =", config.SR_PIVOT_POINTS_ENABLED)
print("SR_SWING_POINTS_ENABLED =", config.SR_SWING_POINTS_ENABLED)
print("VOLUME_FILTER_ENABLED =", config.VOLUME_FILTER_ENABLED)
print("MTF_FILTER_ENABLED =", config.MTF_FILTER_ENABLED)
print("MTF_RSI_FILTER_ENABLED =", config.MTF_RSI_FILTER_ENABLED)
print("MTF_TREND_FILTER_ENABLED =", config.MTF_TREND_FILTER_ENABLED)
print("TREND_FILTER_ENABLED =", config.TREND_FILTER_ENABLED)
